name: andiqu
description: Andi Qu - The Website
# version: 1.0.0
# homepage: https://www.andiqu.com
# author: andi <andi@andiqu.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
